rules: 
  no-extends: 1
  no-trailing-whitespace: 0
  empty-line-between-blocks: 0
  class-name-format: 
    - 1
    -
      convention: 'strictbem'
  property-sort-order: 0
  nesting-depth:
    - 1
    -
      max-depth: 5
  mixins-before-declarations:
    - 1
    -
      exclude: ['tablet', 'mobile']
  no-color-literals:
    - 1
    -
      allow-rgba: true